# Generated by Django 3.2.5 on 2021-08-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210809_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='eircode',
            new_name='postcode',
        ),
    ]
