# Generated by Django 3.2.5 on 2021-08-17 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(default='test')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_course', models.BooleanField(blank=True, default=False, null=True)),
                ('is_apparel', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_option', models.CharField(max_length=255)),
                ('option_name', models.CharField(default='monday', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.IntegerField(default=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='shop.product')),
                ('product_select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productoption')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_select',
            field=models.ManyToManyField(blank=True, related_name='product_options', through='shop.ProductSelect', to='shop.ProductOption'),
        ),
    ]
