# Generated by Django 3.2.5 on 2021-08-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_size_time_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='time',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
