# Generated by Django 3.2.5 on 2021-07-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210728_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparelsize',
            name='stock_count',
            field=models.IntegerField(default=30),
        ),
    ]
