# Generated by Django 3.2.5 on 2021-07-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_apparelsize_stock_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apparel',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sku',
        ),
    ]
