# Generated by Django 3.2.5 on 2021-08-17 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_size_time_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='time',
        ),
        migrations.AlterField(
            model_name='productselect',
            name='product_select',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_selected', to='shop.productoption'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
