# Generated by Django 3.2.5 on 2021-08-04 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_apparelsize_apparel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.AddField(
            model_name='course',
            name='times',
            field=models.ManyToManyField(related_name='course_time', through='shop.CourseTime', to='shop.Time'),
        ),
        migrations.AlterField(
            model_name='coursetime',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_times', to='shop.course'),
        ),
    ]
