# Generated by Django 3.2.5 on 2021-08-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_course_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='course_info',
            field=models.TextField(blank=True, default='test', null=True),
        ),
    ]
