# Generated by Django 3.2.5 on 2021-08-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_course_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course_age',
            field=models.CharField(default='10 years', max_length=255),
        ),
    ]
