# Generated by Django 3.2.5 on 2021-08-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_course_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
