# Generated by Django 3.2.5 on 2021-08-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_apparel_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='time_name',
            field=models.CharField(default='monday', max_length=255),
        ),
    ]
