# Generated by Django 3.2.5 on 2021-08-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_time_time_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_name',
            field=models.CharField(default='small', max_length=255),
        ),
    ]
