# Generated by Django 3.2.5 on 2022-12-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20221227_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='course_info',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
