# Generated by Django 3.2.5 on 2021-08-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210807_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_option', models.CharField(max_length=255)),
                ('option_name', models.CharField(default='monday', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.IntegerField(default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursetime',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursetime',
            name='time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='times',
        ),
        migrations.DeleteModel(
            name='ApparelSize',
        ),
        migrations.DeleteModel(
            name='CourseTime',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AddField(
            model_name='productselect',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='shop.product'),
        ),
        migrations.AddField(
            model_name='productselect',
            name='product_select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_select',
            field=models.ManyToManyField(blank=True, related_name='product_options', through='shop.ProductSelect', to='shop.ProductOption'),
        ),
    ]
