# Generated by Django 3.2.5 on 2022-12-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_course_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='course_info',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_apparel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_course',
            field=models.BooleanField(default=False),
        ),
    ]
