# Generated by Django 3.2.5 on 2022-12-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20221227_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='A brief description of the product'),
        ),
    ]
